<?xml version="1.0" encoding="iso-8859-1"?>
<mosinstall version="1.0.7" type="module">
    <name>swMenuPro</name>
    <version>5.6</version>
    <creationDate>16/10/2007</creationDate>
    <author>Sean White</author>
    <authorEmail>sean@swmenupro.com</authorEmail>
    <authorUrl>http://www.swmenupro.com</authorUrl>
    <copyright>This component is copyright www.swmenupro.com</copyright>
    <license></license>
    <description>Joomla/Mambo DHTML Menu Component</description>
    <files>
        <filename module="mod_swmenupro">mod_swmenupro.php</filename>
        <filename>mod_swmenupro.xml</filename>
        <filename>modules/mod_swmenupro/ClickShowHideMenu.js</filename>
        <filename>modules/mod_swmenupro/ClickShowHideMenu_Packed.js</filename>
        <filename>modules/mod_swmenupro/DropDownMenuX.js</filename>
        <filename>modules/mod_swmenupro/DropDownMenuX_Packed.js</filename>
        <filename>modules/mod_swmenupro/cache/menu.cache</filename>
		<filename>modules/mod_swmenupro/styles/menu.css</filename>
        <filename>modules/mod_swmenupro/dtree.js</filename>
        <filename>modules/mod_swmenupro/dtree_Packed.js</filename>
        <filename>modules/mod_swmenupro/functions.php</filename>
        <filename>modules/mod_swmenupro/ie5.js</filename>
        <filename>modules/mod_swmenupro/ie5_Packed.js</filename>
		<filename>modules/mod_swmenupro/moo.fx.js</filename>
        <filename>modules/mod_swmenupro/moo.fx.pack.js</filename>
		<filename>modules/mod_swmenupro/prototype.lite.js</filename>
        <filename>modules/mod_swmenupro/images/empty.gif</filename>
        <filename>modules/mod_swmenupro/images/no_image.gif</filename>
        <filename>modules/mod_swmenupro/images/transmenu/.grey-40.png</filename>
        <filename>modules/mod_swmenupro/images/transmenu/.white-90.png</filename>
        <filename>modules/mod_swmenupro/images/transmenu/grey-40.png</filename>
        <filename>modules/mod_swmenupro/images/transmenu/submenu-off.gif</filename>
        <filename>modules/mod_swmenupro/images/transmenu/submenu-on.gif</filename>
	<filename>modules/mod_swmenupro/images/transmenu/submenuleft-off.gif</filename>
        <filename>modules/mod_swmenupro/images/transmenu/submenuleft-on.gif</filename>
        <filename>modules/mod_swmenupro/images/transmenu/white-90.png</filename>
        <filename>modules/mod_swmenupro/images/transmenu/x.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/base.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/cd.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/doc.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/empty.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/folder-open.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/folder.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/folderopen.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/globe.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/imgfolder.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/join.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/joinbottom.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/line.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/minus.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/minusbottom.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/musicfolder.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/nolines_minus.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/nolines_plus.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/page.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/plus.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/plusbottom.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/question.gif</filename>
        <filename>modules/mod_swmenupro/images/tree_icons/trash.gif</filename>
        <filename>modules/mod_swmenupro/load_css_script.php</filename>
        <filename>modules/mod_swmenupro/load_script.php</filename>
        <filename>modules/mod_swmenupro/load_script_click.php</filename>
		<filename>modules/mod_swmenupro/load_script_slideclick.php</filename>
        <filename>modules/mod_swmenupro/load_script_gosu.php</filename>
        <filename>modules/mod_swmenupro/load_script_trans.php</filename>
        <filename>modules/mod_swmenupro/load_script_tree.php</filename>
        <filename>modules/mod_swmenupro/menu.js</filename>
        <filename>modules/mod_swmenupro/menu_Packed.js</filename>
        <filename>modules/mod_swmenupro/styles.php</filename>
        <filename>modules/mod_swmenupro/transmenu.js</filename>
        <filename>modules/mod_swmenupro/transmenu_Packed.js</filename>
    </files>
</mosinstall>
