<?php
#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Monday 11th of August 2014 09:16:52 AM

/* !
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
        array(
            "base_url" => "https://" . $_SERVER['HTTP_HOST'] . "/hybridauth/",
            "providers" => array(
                // openid providers
                "OpenID" => array(
                    "enabled" => false
                ),
                "AOL" => array(
                    "enabled" => false
                ),
                "Yahoo" => array(
                    "enabled" => false,
                    "keys" => array("id" => "", "secret" => "")
                ),
                "Google" => array(
                    "enabled" => true,
                    "keys" => array("id" => "496308659122-ro6drm8hpkbalrr4tacdspcl99hkn1ug.apps.googleusercontent.com", "secret" => "gI1flU3VN0bJFIFtoNnsatXa")
                ),
                "Facebook" => array(
                    "enabled" => true,
                    "keys" => array("id" => "1661984670696231", "secret" => "255bc5a26c9cd1a4bf0c338e6dc4a37b")
                ),
                "Twitter" => array(
                    "enabled" => true,
                    "keys" => array("key" => "qqBeF1Ohce5CgBHJBYyWsgwdY", "secret" => "q7MQpQMPShqQs6enH8OKw2vocBA9JZnLy3k99XJzJ7fzjCWTSJ")
                ),
                // windows live
                "Live" => array(
                    "enabled" => false,
                    "keys" => array("id" => "", "secret" => "")
                ),
                "MySpace" => array(
                    "enabled" => false,
                    "keys" => array("key" => "", "secret" => "")
                ),
                "LinkedIn" => array(
                    "enabled" => false,
                    "keys" => array("key" => "", "secret" => "")
                ),
                "Foursquare" => array(
                    "enabled" => false,
                    "keys" => array("id" => "", "secret" => "")
                ),
            ),
            // if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
            "debug_mode" => false,
            "debug_file" => "/mnt/storage/www/dev1.bloomex.ca/hybridauth/error.log"
);
//"keys" => array("id" => "654398764656534", "secret" => "abcf4318ee7db86d1d1a16df38c7c9ba")
